baseURL = 'https://curso-ciencia-basica-f-ciencias-unam.github.io/'
languageCode = 'es-MX'
title = 'Ciencia BÃ¡sica'
defaultContentLanguage = 'es'

theme = 'hugo-book'

[params]


BookTheme = 'light'
BookToC = true
BookLogo = '/img/logo.png'
BookSection = '*'
BookRepo = 'https://github.com/Curso-Ciencia-Basica-F-Ciencias-UNAM/ciencia-basica.git'
BookCommitPath = 'commit'
BookSearch = true
